import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { registerQueryTool } from './query';
import { registerGetCurrentDateTool } from './getCurrentDate';
import { registerGetEmpireResourcesTool } from './getEmpireResources';
import { registerGetEmpireMineralsTool } from './getEmpireMinerals';
import { registerGetEmpireFleetTool } from './getEmpireFleet';
import { registerGetEmpireWealthTool } from './getEmpireWealth';
import { registerGetEmpireFuelTool } from './getEmpireFuel';
import { registerGetSpaceCombatLogTool } from './getSpaceCombatLog';
import { registerGetGroundCombatLogTool } from './getGroundCombatLog';
import { registerGetFighterCombatLogTool } from './getFighterCombatLog';
import { registerGetEmpirePopulationTool } from './getEmpirePopulation';
export const registerTools = (server: McpServer) => {
  registerQueryTool(server);
  registerGetCurrentDateTool(server);
  registerGetEmpireResourcesTool(server);
  registerGetEmpireMineralsTool(server);
  registerGetEmpireFleetTool(server);
  registerGetEmpireWealthTool(server);
  registerGetEmpireFuelTool(server);
  registerGetEmpirePopulationTool(server);
  registerGetSpaceCombatLogTool(server);
  registerGetGroundCombatLogTool(server);
  registerGetFighterCombatLogTool(server);
};
